### ISSUE TITLE
Criticas construtivas

### ISSUE THREAD

**Issue by JhoanDev** [classroom-ufersa/SistemaParqueAquatico#1]
## Feedback sobre o código em C na branch main

1. **Portabilidade para para outros sistemas** Faltou considerar a portabilidade para o sistema Linux. As funções `system("cls")` não são compatíveis com o Linux. É importante utilizar funções que funcionem em ambas as plataformas, como o uso de bibliotecas específicas ou técnicas de limpeza de tela multiplataforma.

2. **Tratamento de entrada de menu:** O programa não trata corretamente entradas inválidas no menu. Por exemplo, ao digitar "1A", o programa ainda prossegue para a opção 1. Seria recomendável implementar tratativas para lidar com entradas inválidas e fornecer uma mensagem de erro adequada ao usuário.

3. **Tratamento de dados de entrada:** Faltou implementar tratativas na leitura dos dados das piscinas e dos clientes para garantir que entradas inválidas, como inserção de caracteres em campos que deveriam conter apenas números, sejam tratadas de forma apropriada.

4. **Unificação do arquivo.txt:** a ideia era utilizar apenas um arquivo txt.

5. **Melhoria na função de edição:** Na função de edição, seria útil solicitar ao usuário qual dado ele deseja editar, em vez de apenas prosseguir com a edição sem questionar. Isso pode melhorar a usabilidade e a experiência do usuário ao interagir com o programa.

No geral, essas são algumas sugestões para aprimorar o código. Parabenizo pelo trabalho realizado!

@roscibely @letsticia @alexrbss

**Comment by alexrbss** [comment]
Boa tarde, fui o responsável pelo código em linguagem C, irei continuar trabalhando no código para realizar as correções e ajustes necessários.  Muito obrigado pelo apontamento.
